import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, expect, test, vi } from 'vitest';
import App from '../App';
import type { Finding } from '../types';
import { topPriorityFindings } from '../utils/risk';

const scan = { id:'scan-1', name:'Demo review', createdAt:'2026-06-26T00:00:00Z', status:'COMPLETED', riskScore:80, riskLevel:'MODERATE', fileCount:1, findingCount:2, aiProvider:'mock', executiveSummary:'Summary', remediationSummary:'Fix things', severityCounts:{HIGH:1,MEDIUM:1}, categoryCounts:{SECRETS:1,API_SECURITY:1}, files:['app.js'], findings:[{id:'finding-1',fileName:'app.js',lineNumber:1,title:'Hardcoded credential',description:'desc',severity:'HIGH',category:'SECRETS',confidence:'HIGH',evidence:'masked',recommendation:'Use secrets manager',secureExample:'Use env vars',status:'OPEN',ruleId:'SEC-002'},{id:'finding-2',fileName:'app.js',lineNumber:2,title:'Wildcard CORS policy',description:'desc',severity:'MEDIUM',category:'API_SECURITY',confidence:'HIGH',evidence:'*',recommendation:'Restrict origins',secureExample:'Use allowlist',status:'OPEN',ruleId:'API-001'}] };
const bedrockScan = { ...scan, aiProvider:'bedrock', executiveSummary:'### Defensive Security Review Summary\n\n**Scan Name:** Portfolio security review\n\n- Prioritize secret rotation', remediationSummary:'**Remediation:**\n\n1. Rotate credentials' };
function renderPath(path='/') { return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[path]}><App /></MemoryRouter></QueryClientProvider>); }
function mockScanResponse(body = scan) { vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}})); }
beforeEach(()=>{ vi.restoreAllMocks(); });

test('landing page renders improved hero and CTAs',()=>{renderPath('/');expect(screen.getByText(/AI-assisted security review for code and cloud config/)).toBeInTheDocument();expect(screen.getByText('Start a review')).toBeInTheDocument();const sampleLink=screen.getByText('Run sample security review').closest('a');expect(sampleLink).toHaveAttribute('href','/scans/new?sample=full-portfolio-demo');});
test('sample selector renders sample options and preloads files',()=>{renderPath('/scans/new?sample=full-portfolio-demo');expect(screen.getByText(/Step 1: Name the review/)).toBeInTheDocument();expect(screen.getByText(/safe demo samples/)).toBeInTheDocument();expect(screen.getAllByDisplayValue('Comprehensive sample review').length).toBeGreaterThan(0);expect(screen.getByDisplayValue('server.js')).toBeInTheDocument();});
test('scan form shows step labels and depth helper text',()=>{renderPath('/scans/new');expect(screen.getByText('Step 2: Add files')).toBeInTheDocument();expect(screen.getByText(/QUICK:/)).toBeInTheDocument();expect(screen.getByText(/Mock AI is used by default/)).toBeInTheDocument();});
test('selecting a sample preloads files',()=>{renderPath('/scans/new');fireEvent.click(screen.getByText('Use sample'));fireEvent.change(screen.getByLabelText('Sample review'),{target:{value:'insecure-terraform'}});expect(screen.getByDisplayValue('main.tf')).toBeInTheDocument();});
test('results page shows risk explanation fix-first provider and details', async()=>{ mockScanResponse(); renderPath('/scans/scan-1'); expect(await screen.findByText('Demo review')).toBeInTheDocument(); expect(screen.getByText(/MODERATE risk based on/)).toBeInTheDocument(); expect(screen.getByText('Fix these first')).toBeInTheDocument(); expect(screen.getAllByText('Summary provider: mock')[0]).toBeInTheDocument(); expect(screen.getAllByText('Evidence').length).toBeGreaterThan(0); expect(screen.getAllByText('Use secrets manager').length).toBeGreaterThan(0); });

test('report actions show PDF and SARIF exports', async()=>{ mockScanResponse(); renderPath('/scans/scan-1'); expect(await screen.findByText('Export PDF report')).toHaveAttribute('href','/api/scans/scan-1/report'); expect(screen.getByRole('button',{name:'Download SARIF'})).toBeInTheDocument(); });
test('SARIF export downloads from the expected endpoint', async()=>{ const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify(scan),{status:200,headers:{'Content-Type':'application/json'}})).mockResolvedValueOnce(new Response(JSON.stringify({version:'2.1.0'}),{status:200,headers:{'Content-Type':'application/json'}})); const createObjectUrl=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:sarif'); const revokeObjectUrl=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{}); renderPath('/scans/scan-1'); fireEvent.click(await screen.findByRole('button',{name:'Download SARIF'})); await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/scans/scan-1/sarif')); expect(createObjectUrl).toHaveBeenCalled(); expect(revokeObjectUrl).toHaveBeenCalledWith('blob:sarif'); });
test('SARIF export failure shows a controlled error', async()=>{ vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify(scan),{status:200,headers:{'Content-Type':'application/json'}})).mockResolvedValueOnce(new Response(JSON.stringify({message:'backend detail'}),{status:500,headers:{'Content-Type':'application/json'}})); renderPath('/scans/scan-1'); fireEvent.click(await screen.findByRole('button',{name:'Download SARIF'})); expect(await screen.findByRole('alert')).toHaveTextContent('Unable to download SARIF export. Please try again.'); expect(screen.queryByText('backend detail')).not.toBeInTheDocument(); });
test('results top findings sorts correctly',()=>{ expect(topPriorityFindings(scan.findings as Finding[])[0].title).toBe('Hardcoded credential'); });
test('results page shows bedrock provider', async()=>{ mockScanResponse(bedrockScan); renderPath('/scans/scan-1'); expect(await screen.findAllByText('Summary provider: bedrock')).toHaveLength(2); });
test('markdown summary renders clean text without raw markers/html', async()=>{ const unsafeScan = { ...bedrockScan, executiveSummary:`### Safe Heading\n\n<script>alert(1)</script>\n\n- Safe item` }; mockScanResponse(unsafeScan); const { container } = renderPath('/scans/scan-1'); expect(await screen.findByRole('heading', { name: 'Safe Heading' })).toBeInTheDocument(); expect(container.querySelector('script')).toBeNull(); expect(container.querySelector('.markdown-summary')?.textContent).not.toContain('###'); });
test('filtered empty state appears', async()=>{ mockScanResponse(); renderPath('/scans/scan-1'); await screen.findAllByText('Hardcoded credential'); fireEvent.change(screen.getByLabelText('Search findings'),{target:{value:'no-match'}}); expect(screen.getByText(/No findings match/)).toBeInTheDocument(); });
test('finding status update behavior', async()=>{ const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async (_input, init)=> init?.method==='PATCH' ? new Response(null,{status:204}) : new Response(JSON.stringify(scan),{status:200,headers:{'Content-Type':'application/json'}})); renderPath('/scans/scan-1'); await screen.findAllByText('Hardcoded credential'); fireEvent.change(screen.getByLabelText('Update status for Hardcoded credential'),{target:{value:'REVIEWED'}}); await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/scans/scan-1/findings/finding-1', expect.objectContaining({method:'PATCH'}))); });
test('error state remains controlled', async()=>{ vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({message:'stack trace'}),{status:500,headers:{'Content-Type':'application/json'}})); renderPath('/scans/missing'); expect(await screen.findByText(/Unable to load this review/)).toBeInTheDocument(); expect(screen.queryByText('stack trace')).not.toBeInTheDocument(); });
